inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
