---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/ideas":
    post:
      summary: Create Idea
      tags:
      - IdeaApi
      description: アイデア登録
      operationId: CreateIdea
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable_entity
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                body:
                  type: string
              required:
              - category_name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
